version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: tgbot
    environment:
      - POSTGRES_USER=tgbot
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tgbot_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: delayed_notifier_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    command:
      - bash
      - -c
      - |
        rabbitmq-plugins enable rabbitmq_delayed_message_exchange --offline
        rabbitmq-server

volumes:
  postgres_data:
  rabbitmq_data: